"""questions json topics array job_jds

Revision ID: 3b77e4aaca07
Revises: 52323e3f641d
Create Date: 2026-07-11 22:53:02.791596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b77e4aaca07'
down_revision: Union[str, None] = '52323e3f641d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_jds', sa.Column('learning', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_jds', 'learning')
    # ### end Alembic commands ###
