"""make priority column non nullable and default 5 in Referral table

Revision ID: 3bf6d29298a0
Revises: 2e24d9a7f627
Create Date: 2026-07-07 03:40:20.969640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf6d29298a0'
down_revision: Union[str, None] = '2e24d9a7f627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
