"""Added LatexPackageUsage Table

Revision ID: 52323e3f641d
Revises: fab1d04ac5f4
Create Date: 2026-07-11 17:34:57.399024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52323e3f641d'
down_revision: Union[str, None] = 'fab1d04ac5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latex_package_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latex_package_usage_package_name'), 'latex_package_usage', ['package_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_latex_package_usage_package_name'), table_name='latex_package_usage')
    op.drop_table('latex_package_usage')
    # ### end Alembic commands ###
