"""changed job transition states

Revision ID: 5442c62a0005
Revises: ff583c04d614
Create Date: 2026-07-19 00:58:25.227828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5442c62a0005'
down_revision: Union[str, None] = 'ff583c04d614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('referral_received', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'referral_received')
    # ### end Alembic commands ###
