"""Add resume_keywords and ResumePreview

Revision ID: 57723eeb31f0
Revises: 6dc913ed951a
Create Date: 2026-08-17 02:02:49.540955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57723eeb31f0'
down_revision: Union[str, None] = '6dc913ed951a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_previews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_latex', sa.Text(), nullable=False),
    sa.Column('section_diffs', sa.JSON(), nullable=False),
    sa.Column('extra_keywords', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_previews_job_id'), 'resume_previews', ['job_id'], unique=False)
    op.create_index(op.f('ix_resume_previews_user_id'), 'resume_previews', ['user_id'], unique=False)
    op.add_column('users', sa.Column('resume_keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_keywords')
    op.drop_index(op.f('ix_resume_previews_user_id'), table_name='resume_previews')
    op.drop_index(op.f('ix_resume_previews_job_id'), table_name='resume_previews')
    op.drop_table('resume_previews')
    # ### end Alembic commands ###
