"""added resume pds fields in users table

Revision ID: 5bf8574d9f4d
Revises: 94b0ab4968bc
Create Date: 2026-07-10 03:24:42.320526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf8574d9f4d'
down_revision: Union[str, None] = '94b0ab4968bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('original_resume_pdf_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('ai_resume_pdf_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_resume_pdf_url')
    op.drop_column('users', 'original_resume_pdf_url')
    # ### end Alembic commands ###
