"""Add linkedin message in users table

Revision ID: 6dc913ed951a
Revises: 964523925b86
Create Date: 2026-08-02 03:44:40.605578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc913ed951a'
down_revision: Union[str, None] = '964523925b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_message', sa.Text(), server_default="I'm exploring opportunities and would love to connect", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_message')
    # ### end Alembic commands ###
