"""removed these fields - original_resume_pdf_url, encrypted_google_search_api_key, google_search_engine_id

Revision ID: 94b0ab4968bc
Revises: 3bf6d29298a0
Create Date: 2026-07-10 02:13:43.534299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b0ab4968bc'
down_revision: Union[str, None] = '3bf6d29298a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_resume_latex_url', sa.Text(), nullable=True))
    op.drop_column('users', 'original_resume_pdf_url')
    op.drop_column('users', 'encrypted_google_search_api_key')
    op.drop_column('users', 'google_search_engine_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_search_engine_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('encrypted_google_search_api_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('original_resume_pdf_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'ai_resume_latex_url')
    # ### end Alembic commands ###
