"""Add comany role and workday_job_id to job_jd table from job table

Revision ID: 96d009568658
Revises: 3b77e4aaca07
Create Date: 2026-07-11 23:56:34.974214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d009568658'
down_revision: Union[str, None] = '3b77e4aaca07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_jds', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('job_jds', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column('job_jds', sa.Column('workday_job_id', sa.String(length=255), nullable=True))
    op.drop_column('jobs', 'role')
    op.drop_column('jobs', 'company')
    op.drop_column('jobs', 'workday_job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('workday_job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('job_jds', 'workday_job_id')
    op.drop_column('job_jds', 'role')
    op.drop_column('job_jds', 'company')
    # ### end Alembic commands ###
