"""added current_llm_model fields in users table

Revision ID: fab1d04ac5f4
Revises: 5bf8574d9f4d
Create Date: 2026-07-10 04:22:48.278441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab1d04ac5f4'
down_revision: Union[str, None] = '5bf8574d9f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_llm_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_llm_model')
    # ### end Alembic commands ###
