"""changing team_signal to extracted_department

Revision ID: ff583c04d614
Revises: c037798e8b1d
Create Date: 2026-07-15 02:10:26.518715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff583c04d614'
down_revision: Union[str, None] = 'c037798e8b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_jds', sa.Column('extracted_department', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('job_jds', 'team_signals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_jds', sa.Column('team_signals', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('job_jds', 'extracted_department')
    # ### end Alembic commands ###
